### ISSUE TITLE
How to obtain the dataset?

### ISSUE THREAD

**Issue by yul1998** [penghu-cs/RCL#1]
![image](https://github.com/penghu-cs/RCL/assets/71552069/9bd8359f-0f5e-4ddf-9de9-edff578eb8f9)
Dear author, thanks for your amazing work! I encountered an issue with the image above when obtaining the dataset. Is there any other way to obtain the dataset?

**Comment by QinYang79** [comment]
> ![image](https://user-images.githubusercontent.com/71552069/273954204-9bd8359f-0f5e-4ddf-9de9-edff578eb8f9.png) Dear author, thanks for your amazing work! I encountered an issue with the image above when obtaining the dataset. Is there any other way to obtain the dataset?

https://github.com/Paranioar/SGRAF/tree/main/vocab
